# << general >>
num_cem_iter               : 5
planning_horizon           : 30
dim_action                 : 2
dimension_of_interst       : [0, 1]

colored_noise_exponent     : 3.0

lower_bound_sampling       : -0.1
upper_bound_sampling       :  0.1
lower_bound_action         : -1.0
upper_bound_action         :  1.0
lower_bound_simulated_path : -0.06
upper_bound_simulated_path : 0.06

# << sampling >>
num_sample                 : 300
decay_sample               : 1.25

# << elite >>
num_elite                  : 3
fraction_rate_elite        : 1.0

# << update distribution >>
alpha                      : 0.1
init_std                   : 0.4

# << other >>
debug                      : False
verbose                    : True
verbose_additional         : False
save_visualization_dir     : "./fig"

