# << general >>
num_cem_iter               : 7
planning_horizon           : 25
dim_action                 : 3
dimension_of_interst       : [0, 1, 2]

colored_noise_exponent     : [0.0, 1.0, 2.5, 3.5]

lower_bound_nominal_with_noise :  -0.2
upper_bound_nominal_with_noise :   0.2

lower_bound_sampling       :  -0.05
upper_bound_sampling       :   0.05
lower_bound_simulated_path :
upper_bound_simulated_path :
dim_path                   : 1

# << sampling >>
num_sample                 : 200
decay_sample               : 1.25

# << sampling >>
num_subparticle            : 10
std_subparticle            : 0.015

# << elite >>
num_elite                  : 1
fraction_rate_elite        : 1.0

# << update distribution >>
alpha                      : 0.5 # save rate of previous mean
init_std                   : 0.25

# << other >>
figsize_path               : [5, 5]
debug                      : False
verbose                    : True
verbose_additional         : False
save_visualization_dir     : "./fig"
is_verbose_newline         : True
